from .auth import router as auth_router
from .caja_diaria import router as caja_diaria_router
from .sales import router as sales_router
from .purchases import router as purchases_router
from .payroll import router as payroll_router
from .vacations import router as vacations_router
from .expenses import router as expenses_router
from .dashboard import router as dashboard_router
from .employees import router as employees_router
from .receipts import router as receipts_router
from .cashflow import router as cashflow_router
from .vencimientos import router as vencimientos_router
from .gastos_personales import router as gastos_personales_router
from .cupones import router as cupones_router
from .clientes import router as clientes_router
from .marketing import router as marketing_router
